### PR TITLE
Fix performance issues around the LambdaReleasePool in EcmascriptEngine.

### LINKED ISSUE #79: Hot Reload Hang on MacOS
I'm finding that during a hot reload on MacOS, Xcode just hangs in a permanent loop and the project freezes.

Dropping the debugger in shows that we're stuck in the Duktape finalizer callstack searching through the `lambdaReleasePool`, but it seems like there are a million things to be finalized. It looks like there indeed might be a bug with the lambdaReleasePool, because it's huge, but I'm not sure that's exactly what's hanging up Xcode here.

@JoshMarler have you seen this one?

### PR DESCRIPTION
**Pull request by JoshMarler**
This fix resolves #79. The freeze was caused by an O(Nsquared) lookup
 on the LambdaReleasePool vector when GC kicked in and triggered our
 LambdaReleasePool finalizers.

 Note this also bumps juce from 5.4.1 to 5.4.2 as std::hash
 specialisation for juce::Uuid was added to the Uuid header in 5.4.2.

### CODE REVIEW

File: blueprint/core/blueprint_EcmascriptEngine.h [hunk 1]
```diff
@@ -153,11 +154,12 @@ namespace blueprint
             static duk_ret_t callbackFinalizer (duk_context* ctx);
 
             juce::var::NativeFunction callback;
+            juce::Uuid                id;
         };
 
         //==============================================================================
         duk_context* ctx;
-        std::vector<std::unique_ptr<LambdaHelper>> lambdaReleasePool;
+        std::unordered_map<juce::Uuid, std::unique_ptr<LambdaHelper>> lambdaReleasePool;
```
Comment (JoshMarler) [inline blueprint/core/blueprint_EcmascriptEngine.h:162]: @nick-thompson, went for `unordered_map` in the end as it's easier to use with `unique_ptr`. I decided against a static counter in `LambdaHelper` as the key for the moment, could be inflexible in the future with multiple `EcmascriptEngine` instances? i.e. if you have multiple ReactApplicationRoot instances in your app etc.  

Had to bump juce to 5.4.2 to include the `std::hash` specialisation for `juce::Uuid`. Could use something else if necessary but I think this is OK ?

Comment (nick-thompson) [reply blueprint/core/blueprint_EcmascriptEngine.h:162]: Nice, I like it!

Yep, happy for the bump to 5.4.2. I want to bump to 6.x soon (#36) with CMake soon anyway. That should also make #22 quite easy. Much to do! :)
